# Generated by Django 5.1.3 on 2025-05-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('nss_unit', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField()),
                ('password', models.CharField(max_length=255)),
                ('confirm_password', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Coordinator',
                'verbose_name_plural': 'Coordinators',
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Unknown', max_length=200)),
                ('nss_unit_number', models.CharField(max_length=100)),
                ('admission_number', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('email_id', models.EmailField(default='notprovided@example.com', max_length=200)),
                ('address', models.TextField(default='Not provided')),
                ('blood_group', models.CharField(default='Not provided', max_length=5)),
                ('class_advisor', models.CharField(default='Not assigned', max_length=200)),
                ('username', models.CharField(default='default_username', max_length=150, unique=True)),
                ('password', models.CharField(default='', max_length=255)),
                ('confirm_password', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
