# Generated by Django 5.1.3 on 2025-05-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='confirm_password',
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='email_id',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
