# Generated by Django 5.1.3 on 2025-05-06 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_volunteer_confirm_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinator',
            name='username',
            field=models.CharField(default='default_username', max_length=150, unique=True),
        ),
    ]
