# Generated by Django 5.1.3 on 2025-05-06 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_event1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event1',
            new_name='Program',
        ),
    ]
