# Generated by Django 5.1.3 on 2025-05-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense'), ('Donation', 'Donation'), ('Misc', 'Misc')], max_length=50)),
            ],
        ),
    ]
