# Generated by Django 5.1.3 on 2025-05-06 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_financialrecord'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'event')},
        ),
    ]
