# Generated by Django 5.1.3 on 2025-05-12 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_alter_attendance_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Program',
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
