# Generated by Django 5.1.3 on 2025-05-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_delete_program_alter_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registered_students',
            field=models.ManyToManyField(blank=True, to='project.student'),
        ),
    ]
