# Generated by Django 5.1.3 on 2025-05-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_remove_event_registered_students_alter_event_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100, unique=True)),
                ('student_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='coordinator',
            name='date_of_birth',
            field=models.CharField(default='Not Provided', max_length=15),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='date_of_birth',
            field=models.CharField(default='Not Provided', max_length=15),
        ),
    ]
