# Generated by Django 5.1.3 on 2025-05-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_student_coordinator_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
