# Generated by Django 5.1.3 on 2025-05-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_volunteer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinator',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
