# Generated by Django 5.1.3 on 2025-05-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_coordinator_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinator',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='phone',
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='No location provided', max_length=255),
        ),
    ]
