# Generated by Django 5.1.3 on 2025-05-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_remove_coordinator_phone_remove_volunteer_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='course',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='roll_number',
            field=models.CharField(default='UNKNOWN', max_length=100),
        ),
    ]
