# Generated by Django 5.1.3 on 2025-05-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_volunteer_course_volunteer_roll_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(default='00:00'),
        ),
    ]
